const usersActionTypes = {
  USERS_LOAD_START: "USERS_LOAD_START",
  USERS_LOAD_SUCCESS: "USERS_LOAD_SUCCESS",
  USERS_LOAD_ERROR: "USERS_LOAD_ERROR",
  LOAD_CURRENT_USER: "LOAD_CURRENT_USER",
  LOAD_CURRENT_USER_SUCCESS: "LOAD_CURRENT_USER_SUCCESS",
  LOAD_CURRENT_USER_ERROR: "LOAD_CURRENT_USER_ERROR",
};
export default usersActionTypes;
